# -*- coding: utf-8 -*-
"""DEPI_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZN39j3carZcc0zsQDoxMWtVtah99rcR
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/twcs.csv')

print(len(df))

customers = df[df['inbound'] == True]
support = df[df['inbound'] == False]

merged = customers.merge(
    support,
    left_on='tweet_id',
    right_on='in_response_to_tweet_id',
    how='inner'
)

final_df = merged[['text_x', 'text_y', 'author_id_y']]
final_df.columns = ['question', 'answer', 'company']

print(final_df.head())

print(len(final_df))

amazon_df = final_df[final_df['company'] == 'AmazonHelp']

print(amazon_df.head())

print(len(amazon_df))

!pip install langdetect
from langdetect import detect

def is_english(text):
    try:
        return detect(text) == 'en'
    except:
        return False

amazon_df = amazon_df[
    amazon_df['question'].apply(is_english) &
    amazon_df['answer'].apply(is_english)
]

print(len(amazon_df))

print(amazon_df.head())

amazon_df.to_csv("amazon_final_data.csv", index=False)

from google.colab import files
files.download("amazon_final_data.csv")